texts = {
    "intro_title": "La Historia de Chris Morris, el Hámster Melódico\n",
    "intro_1": "En un pequeño departamento de la ciudad, vivía Chris Morris, un hámster con una personalidad única.\n",
    "intro_2": "A pesar de su desaliño, siempre llevaba una cartera de colores vivos y un moño rosado.\n",
    "intro_3": "Podría parecer que solo quería impresionar, pero era su forma de mostrar que no le importaba lo que pensaran los demás.\n",
    "intro_4": "Chris compartía su hogar con su dueño, quien era fan de Radiohead. Cada tarde, mientras sonaban las melodías de la banda,\n",
    "intro_5": "Chris se movía inquieto en su rueda, sintiendo el pulso de la música que también le encantaba. Era su momento de libertad.\n",
    "intro_6": "Sin embargo, había una perra chow chow que capturaba su atención desde la ventana...\n",
    "intro_choice": "¿Qué decides hacer?\n",
    "choice_1": "1. Escuchar Radiohead desde el rincón de la jaula.",
    "choice_2": "2. Escapar para explorar el jardín bajo la luz de la luna.",
    "stay_1": "\nTe quedas en la jaula, moviendo tus patitas al ritmo de 'Creep'.",
    "stay_2": "Aunque la música es reconfortante, algo dentro de ti te dice que esta noche es especial.\n",
    "stay_choice_1": "1. Cambiar de opinión y escapar.",
    "stay_choice_2": "2. Quedarte y dormir.\n",
    "stay_end_1": "\nTe duermes mientras la música sigue sonando...",
    "stay_end_2": "Quizás nunca sabrás qué habría pasado si hubieras seguido ese instinto.",
    "stay_end_3": "Fin del juego. Chris Morris eligió la comodidad del hogar.",
    "escape_1": "\nEmpujas la puerta de tu jaula y das un salto hacia la libertad.",
    "escape_2": "El jardín se extiende ante ti, iluminado por la luna. El aire fresco llena tus pulmones.\n",
    "escape_choice_1": "1. Ir al árbol donde conociste al chow chow.",
    "escape_choice_2": "2. Explorar las flores en el jardín de la vecina.\n",
    "chow_1": "\nTe acercas al árbol donde conociste al chow chow.",
    "chow_2": "Recuerdas cómo te miraba con curiosidad, como si entendiera tu pequeño corazón.",
    "chow_3": "Las hojas crujen bajo tus patas mientras un suave viento acaricia tu pelaje.",
    "chow_4": "De repente, escuchas a lo lejos 'Creep' nuevamente... es tu dueño.",
    "chow_5": "Sientes paz. Has vivido una buena vida.\n",
    "chow_choice_1": "1. Caminar hacia el jardín de la vecina.",
    "chow_choice_2": "2. Quedarte aquí y contemplar el cielo.\n",
    "garden_1": "\nLlegas al jardín de la vecina. Las flores huelen dulces y el ambiente está en calma.",
    "garden_2": "Aquí fue donde conociste al chow chow por primera vez.",
    "garden_3": "Te acurrucas entre las flores mientras escuchas los últimos acordes de 'Creep'.",
    "garden_4": "Recuerdas a tu dueño, la dueña del chow chow y a tu amiga peluda.\n",
    "garden_5": "Cerrando los ojos por última vez, piensas: 'Qué vida tan maravillosa tuve.'\n",
    "garden_6": "Fin del juego. Chris Morris encontró su final en paz y rodeado de recuerdos hermosos.",
    "peaceful_1": "\nMiras las estrellas desde el árbol, sintiendo que esta es la última noche de tu vida.",
    "peaceful_2": "Las memorias llenan tu corazón: el amor por la música, tus dueños, el chow chow...",
    "peaceful_3": "Cerrando los ojos, te dejas llevar por la melodía de Radiohead.",
    "peaceful_4": "Fin del juego. Chris Morris descansó en paz, celebrando una vida inolvidable.",
    "invalid_choice": "Opción no válida. Elige de nuevo.\n",
    "end_input": "Pulsa ENTER para salir",
}
